#!/bin/env bash

source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33mFile 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

USER_FILE="${HOME}/.UMBRELLA/UMBRELLA/passwd"
ENCRYPT_KEY="dynamic_key"
fuser=$(grep "USER" ${UMBRELLA}/passwd|tail -n 1)

show_help() {
  echo -e "${yellow}For more help, type ${green}UMBRELLA${yellow} [${red}-h${yellow} | ${red}--help${yellow}] for help UMBRELLA CORPORATION.${default}"
}

encrypt_username() {
  local user="$1"
  local fuser=$(grep "USER" ${UMBRELLA}/passwd|tail -n 1)
  local encrypted=$(echo $user|openssl enc -aes-256-cbc -md sha512 -a -pbkdf2 -iter 100000 -salt -pass pass:dynamic_key)
  sed -i "s|$fuser|USER : $encrypted|" ${UMBRELLA}/passwd
  log -d "Username saved successfully."
}

validate_input() {
  local input="$1"
  if [[ -z "$input" ]]; then
    error "Input cannot be empty. Please try again."
    return 1
  fi
  return 0
}

get_username() {
  while read -p "Input username: " user && ! validate_input "$user"; do
    continue
  done
  echo "$user"
}

remove_username() {
  if [[ -n "$(grep "USER" ${UMBRELLA}/passwd|tail -n 1|awk 'NF{print NF}')" ]]; then
    sed -i "s|$fuser|USER |" ${UMBRELLA}/passwd
    log -d "Username removed successfully."
  else
    log "${red}[✖] ${yellow}You don't have a defined username."
  fi
}

handle_options() {
  case "$1" in
    -n|--new)
      if [[ -z "$(grep "USER" ${UMBRELLA}/passwd|tail -n 1|awk 'NF{print NF}')" ]]; then
        read -p "[Y/N] Do you want to change your username? " opt
        if [[ "$opt" =~ ^[Yy]$ ]]; then
          user=$(get_username)
          encrypt_username "$user"
        else
          log "$red[✖] ${yellow}Username remains unchanged.${default}"
        fi
      else
        user=$(get_username)
        encrypt_username "$user"
      fi
      ;;
    -r|--remove)
      read -p "[Y/N] Do you want to delete your username? " opt
      if [[ "$opt" =~ ^[Yy]$ ]]; then
        remove_username
      else
        log "$red[✖] ${yellow}Username deletion canceled!.${default}"
      fi
      ;;
    -h|--help)
      show_help
      ;;
    *)
      info
      exit 1;
      ;;
  esac
}

# Inicio del script
if [[ -z "$1" ]]; then
  show_help
else
  handle_options "$1"
fi
