#!/usr/bin/bash
#

lightb=#ffffff
lightf=#000000
cursor=#2f4f4f

colorc=$(grep "cursor" ~/.termux/colors.properties | tail -n 1)
colorb=$(grep "background" ~/.termux/colors.properties | tail -n 1)
colorf=$(grep "foreground" ~/.termux/colors.properties | tail -n 1)


sed -i "s|$colorc|cursor = ${cursor}|" ~/.termux/colors.properties
sed -i "s|$colorf|foreground = ${lightf}|" ~/.termux/colors.properties
sed -i "s|$colorb|background = ${lightb}|" ~/.termux/colors.properties

termux-reload-settings
