#!/usr/bin/env bash

source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33mFile 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

check_dependencies proot-distro

distro() {
  local a=$(mktemp);
  log -a "Check files rootfs"
  if [ -d ${PREFIX}/var/lib/proot-distro/installed-rootfs ]; then
    command ls ${PREFIX}/var/lib/proot-distro/installed-rootfs &> $a;
  else
    error -l "Directory 'installed-rootfs' does not exist!. You need install rootfs, run proot-distro list."
    exit 1
  fi

  b="$(awk '{print $1}' < "$a")"
  log -a "Check files home distribution"
  if [ -d ${PREFIX}/var/lib/proot-distro/installed-rootfs/${b}/home ]; then
    command ls ${PREFIX}/var/lib/proot-distro/installed-rootfs/${b}/home > $a;
    b="$(awk '{print $1}' < "$a")";
    exec proot-distro login debian --user ${b};
  else
    error -l "You have to install a distribution. Run ${green}pkg2install ${red}distro."
    exit 1
    fi
  exec rm ${a} &>/dev/null;
}

distro
