#!/usr/bin/bash
#
db=#1a1b26
df=#c0caf5
cu=#9400d3

b=$(grep "background" ~/.termux/colors.properties | tail -n 1)
f=$(grep "foreground" ~/.termux/colors.properties | tail -n 1)
c=$(grep "cursor" ~/.termux/colors.properties | tail -n 1)

sed -i "s|$c|cursor = ${cu}|" ~/.termux/colors.properties
sed -i "s|$f|foreground= ${df}|" ~/.termux/colors.properties
sed -i "s|$b|background = ${db}|" ~/.termux/colors.properties

termux-reload-settings
