#!/usr/bin/env bash
#
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' does not exist!.\033[0m\n"; exit 1; }

check_dependencies termux-toast
check_dependencies openssl

usage() {
	printf "${yellow}USAGE:${green} password ${yellow}[ ${red}-g${yellow} | ${red}-s${yellow} | ${red}-n${yellow} ] password for login in UMBRELLA SHELL.
  For more help type ${green}UMBRELLA${yellow} [ ${red}-h${yellow} | ${red}--help${yellow} ] for helpper UMBRELLA CORPORATION.
	
  OPTIONS:
  ${red}-s${yellow} ┆┄┄┄┄┄┄┆ ${red}--set${yellow}    ┆┅┅┅┅┅┅┆ Set password for login, enable or disable.
  ${red}-n${yellow} ┆┄┄┄┄┄┄┆ ${red}--new${yellow}  ┆┅┅┅┅┅┅┆ Create new password. ${default}\n\n";}

if [[ -z "$1" ]]; then usage ; exit 1 ;fi


case $1 in
  -h|--help)
    usage
    exit 0
    ;;
  -s|--set)
    theme cyan
    pass Set
    ;;
  -n|--new)
    pass New
    ;;
  *)
    usage ; info ; exit 1;
    ;;
esac


