#!/data/data/com.termux/files/usr/bin/bash
#
source ${HOME}/.UMBRELLA/UMBRELLA/variables
source ${UMBRELLA}/functions
COMMANDS termux-toast termux-api
COMMANDS openssl openssl-tool

HELP() {
	printf "${yellow}USAGE: ${green}password${yellow} [ ${red}-g${yellow} | ${red}-s${yellow} | ${red}-n${yellow} ] password for login in UMBRELLA SHELL.
  For more help type ${green}UMBRELLA${yellow} [ ${red}-h${yellow} | ${red}--help${yellow} ] for helpper UMBRELLA CORPORATION.
	
  OPTIONS:
  ${red}-g${yellow} ┆┄┄┄┄┄┄┆ ${red}--get${yellow}    ┆┅┅┅┅┅┅┆ Get password
  ${red}-s${yellow} ┆┄┄┄┄┄┄┆ ${red}--set${yellow}    ┆┅┅┅┅┅┅┆ Set password for login, enable or disable.
  ${red}-n${yellow} ┆┄┄┄┄┄┄┆ ${red}--new${yellow}  ┆┅┅┅┅┅┅┆ Create new password. ${default}\n\n";}

[[ -z $1 ]] && { HELP; exit 1; }

[[ -n $1 ]] && {
	case "$1" in
		-h|--help)
			HELP;
			exit 0;
		  ;;
		-g|--get)
			trap ctrl_c 2;
theme cyan
			ctrl_c(){ pass Get; }
			pass Get
			;;
		-s|--set)
theme cyan
			pass set
			;;
		-n|--new)
			pass New
			;;
		*)
			about
			;;
	esac
}

