#!/usr/bin/bash

sepiaf=#000000
sepiab=#ffdab9
cursor=#000000

colorb=$(grep "background" ~/.termux/colors.properties | tail -n 1)
colorf=$(grep "foreground" ~/.termux/colors.properties | tail -n 1)
colorc=$(grep "cursor" ~/.termux/colors.properties | tail -n 1)

sed -i "s|$colorc|cursor = ${cursor}|" ~/.termux/colors.properties
sed -i "s|$colorf|foreground= ${sepiaf}|" ~/.termux/colors.properties
sed -i "s|$colorb|background = ${sepiab}|" ~/.termux/colors.properties

termux-reload-settings
