#!/bin/bash
#
source ${HOME}/.UMBRELLA/UMBRELLA/functions || { echo -en "\033[31mError:\033[33mFile 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

declare -A THEMES=(
  ["cyan"]="theme cyan"
  ["red"]="theme red"
  ["dark"]="theme dark"
)

disable='#theme'

declare -A change=(
  ["Login"]=$(grep "theme" ${libexec}/UMBRELLA.login|tail -n 1)
  ["Help"]=$(grep "theme" ${libexec}/functions/UMBRELLA|tail -n 1)
  ["Passw"]=$(grep "theme" ${libexec}/functions/password|tail -n 1)
)

list_themes() {
  echo -en "${yellow}Available themes: "
  for theme in "${!THEMES[@]}"; do
    echo -en "${blue}$theme${default} "
  done
  echo
}

main() {
  local color=$1
  if [[ -z "${THEMES[$color]}" ]]; then
    error "Color not valid."
    list_themes
    exit 1
  fi

  local files=("${libexec}/UMBRELLA.login" "${libexec}/functions/UMBRELLA" "${libexec}/functions/password")
  check_file "${files[@]}"

  sed -i "s|${change[Login]}|${THEMES[$color]}|" ${libexec}/UMBRELLA.login
  sed -i "s|${change[Help]}|${THEMES[$color]}|" ${libexec}/functions/UMBRELLA
  sed -i "s|${change[Passw]}|${THEMES[$color]}|" ${libexec}/functions/password

  log "Theme change to $color."
}

toggle_theme() {
  select opt in Enable Disable Exit; do
    case "$opt" in
      Exit)
        exit 0
        ;;
      Disable)
        sed -i "s|${change[Login]}|$disable|" ${libexec}/UMBRELLA.login
        log -d "Disable theme"
        break
        ;;
      Enable)
        main "$red"
        log -d "Enable theme"
        break
        ;;
      *)
        error "No valid option!. Try again.${default}"
        ;;
    esac
  done
}

if [[ -z "$1" ]]; then
  echo -e "${red}(⋯☣)${yellow}Input theme color, run ${green}theme ${red}-c <color>${default}\n"
  info
  exit 1;
fi

case "$1" in
  -c|--color)
    if [[ -z "$2" ]]; then
      error "You must specify a color."
      list_themes
      exit 1;
    fi
    main "$2"
    ;;
  -s|--set)
    toggle_theme
    ;;
  -l|--list)
    list_themes
    ;;
  *)
    error "No valid option '$1'."
    echo -e "${yellow}Input theme color, run ${green}theme ${red}-c <color>${default}\n"
    info
    exit 1
    ;;
esac
