#!/bin/bash
#
source ${HOME}/.UMBRELLA/UMBRELLA/functions
source ${UMBRELLA}/variables
   [[ -z $1 ]] && {
   theme cyan;
   helpper;
   exit 1;
 }
   [[ -n $1 ]] && {
   if [ $1 = '-h' ] || [ $1 = '--help' ]; then
theme cyan
     helpper;
     exit 0;
   elif [ $1 = '-v' ] || [ $1 = '--version' ]; then
     printf "${yellow}☣ U M B R E L L A  C O R P O R A T I O N ☣\n$version © 2023 by LAWRENCE COROY${default}\n"
	 else
		 about
	 fi
 }
