#!/usr/bin/env bash

a=$(mktemp);
if [ -d /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs ]; then
  command ls /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs &> $a;
fi

b="$(cat $a | awk '{print $1}')";
if [ -d /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/${b}/home ]; then
  command ls /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/${b}/home > $a;
  b="$(cat $a | awk '{print $1}')";
# Kill open X11 processes
  kill -9 $(pgrep -f "termux.x11") 2>/dev/null;
#Enable PulseAudio over Network
  pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
#Prepare termux-x11 session
  export XDG_RUNTIME_DIR=${TMPDIR}
  termux-x11 :0 >/dev/null &
# Wait a bit until termux-x11 gets started.
  sleep 3
#Launch Termux X11 main activity
  am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
  sleep 1
# Login in PRoot Environment. Do some initialization for PulseAudio, /tmp directory
# and run XFCE4 as user.
# See also: https://github.com/termux/proot-distro
# Argument -- acts as terminator of proot-distro login options processing.
# All arguments behind it would not be treated as options of PRoot Distro.
  proot-distro login debian --shared-tmp -- /bin/bash -c 'export PULSE_SERVER=127.0.0.1 && export XDG_RUNTIME_DIR=${TMPDIR} && su - '${b}' -c "env DISPLAY=:0 startxfce4"'
  exit 0;
  exec rm ${a} &>/dev/null;
else
  echo -en "\e[0;33mYou have to install desktop distro. Run \e[0;34mpkg2install \e[0;31mX11_distro.\e[0m\n"
fi

