#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/variables" || { echo -en "\033[31mError:\033[33m File 'variables' is required but not exist!.\033[0m\n" ; exit 1; }

log() {
  local argv="$1"
  echo -e "${blue}$argv${default}"
}
export -f log

error() {
  local argv="$1"
  log "$E $argv"
}
export -f error

log_data() {
  if [ ! -f "$LOGFILE" ]; then touch "$LOGFILE"; fi
  local message="$1"
  echo "[ $(date '+%Y-%m-%d %H:%M:%S') ] : $message" >> "$LOGFILE"
}
export -f log_data

check_file() {
  local files=("$@")
  for file in "${files[@]}"; do
    log_data "Checking file $file"
    if [ ! -f "$file" ]; then
      echo -en "\033[31m[✖] Error:\033[33mFile '$file' is required but not exist!."
      exit 1;
    fi
  done
}
export -f check_file

info() {
  echo -en "${yellow}For more help type ${green}UMBRELLA${yellow} [${red} -h${yellow} |${red} --help${yellow} ] for helpper UMBRELLA CORPORATION.${default}\n"
}
export -f info

theme() {
  local files=("${BANNER}/dark" "${BANNER}/cyan" "${BANNER}/red")
  local argv="$1"
  check_file "$files"
  declare -A color=(
  ["dark"]="${BANNER}/dark"
  ["red"]="${BANNER}/red"
  ["cyan"]="${BANNER}/cyan"
)
  bash "${color[$argv]}"
  sleep 0.5;
}
export -f theme

update_system() {
  log "$A Update system ... "
  if ! pkg update && upgrade -y &>>"$LOG_FILE"; then
    error "The dependencies could not be updated!."
  fi
}
export -f update_system

check_dependencies() {
  local argv=("$@")
  for dep in "${argv[@]}"; do
    log_data "Checking $dep "
    if ! command -v "$dep" &>/dev/null; then
      echo -en "${red}[✖] Error:${yellow} '$dep' is required but not installed. ${default}\n"
      exit 1;
    fi
  done
}
export -f check_dependencies

install_dependencies() {
  local dependencies=("$@")

  for dep in "${dependencies[@]}"; do
    log_data "Checking $dep "
    if command -v "$dep" &>/dev/null; then
      log "$D $dep Already is installed!."
    else
      log "$A Installing dependencies $dep...  "
      if ! pkg install -y "$dep"; then
        error "Could not be installed '$dep'."
      fi
      log "$D $dep Installed Successfully!."
    fi
  done
}
export -f install_dependencies

helpper() {
  printf "${yellow}☣ U M B R E L L A ☣ C O R P O R A T I O N ☣ ${version} (c) by LAWRENCE •‣ It is a custom configuration tool that makes it simple to perform basic tasks. At Umbrella Corporation we believe that nothing is impossible. If you can imagine it, you can create it!. The following is the help menu that provides you with the available tools that you can use to make using our tool easier.\nSyntax: COMMANDS [-args-] [-descriptions-]\n 

\n✲ THIS COMMANDS THERE FOR PERSONALITYON TO UMBRELLA CORPORATION ✲
	       ✲ Settings Opctions ✲
   COMMANDS    ∵   ARGUMENTS    ∵   DESCRIPTION

  ❉ ${green}UMBRELLA${yellow}     ┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-h  ${yellow}| ${red}--help${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Help from UMBRELLA CORPORATION.
  ❉ ${green}adduser${yellow}     ┄┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-n  ${yellow}| ${red}--new${yellow}  ┆┅┅┅┅┅┄┄┄┄┇ Add a username.
                            ┆${red}-r ${yellow}| ${red}--remove${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Remove your username.
  ❉ ${green}check-data${yellow}   ┄┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Show the processes and data made of changes or customization of UMBRELLA CORPORATION.
                            ┆ ${red}-h${yellow}--| ${red}--help${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Menu help check-data.
  ❉ ${green}password${yellow}     ┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-n  ${yellow}| ${red}--new  ${yellow}┆┅┅┅┅┅┄┄┄┄┇ Add/get a password to log in to login UMBRELLA.
                            ┆  ${red}passwd set${yellow}  ┆┅┅┅┅┅┄┄┄┄┇ Set mode enable/password in login.
  ❉ ${green}theme${yellow}        ┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-c ${yellow}| ${red}--color${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Set a banner color that providedUMBRELLA CORPORATION. Available colors: cyan, red and dark.
                            ┆ ${red}-s${yellow}  | ${red}--set${yellow}  ┆┅┅┅┅┅┄┄┄┄┇ Set mode enable/disable or costum, for the UMBRELLA wall banner.
  ❉ ${green}tools${yellow}        ┄┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Tools that Umbrella Corporation can provide you.
                            ┆ ${red}-h${yellow}  | ${red}--help${yellow} ┆┅┅┅┅┅┄┄┄┄┇ For more help of tools.
  ❉ ${green}version${yellow}      ┄┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Show version UMBRELLA installed.

  \n✲ THIS COMMANDS THERE FUNCTIONS TO UMBRELLA CORPORATION ✲
                 ✲ Commands ✲
   COMMANDS             ∵           DESCRIPTION$D
  ❉ ${green}archivos${yellow}      ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ File management of your Android.
  ❉ ${green}apkinf${yellow}        ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Provides information on phone applications.
  ❉ ${green}df${yellow}            ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ It is a tool that shows information about the available and total space in a file system.
  ❉ ${green}distro${yellow}       ┄┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Utility that allows you to run a Linux distribution on an Android device without requiring root access.
  ❉ ${green}fzf-lovely${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ It is a flexible tool that allows you to search for files, navigate processes, complete routes automatically.
  ❉ ${green}lock${yellow}          ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇  Block termux.
  ❉ ${green}localhost${yellow}     ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Show your public internet protocol.
  ❉ ${green}p10k  ${yellow}        ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ To access the settings of Powerlevel10k is a theme for Zsh.
  ❉ ${green}pkg2install${yellow}   ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ About packages provided by UMBRELLA CORPORATION.
  ❉ ${green}tree${yellow}          ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ File Map/Map Display.
  ❉ ${green}tldr${yellow}          ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Command Manual/Command Usage.
  ❉ ${green}traductor${yellow}     ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Init a command line traductor.
  ❉ ${green}X11_distro${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Utility that lets you run your Linux distribution in a desktop environment.
  ❉ ${green}X11_native${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ It is a tool that allows you to run a Linux environment on an Android device.
  ┇┄┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇${default}\n\n"
}
export -f helpper

pass () {
  files=("${libexec}/UMBRELLA.login" "${UMBRELLA}/passwd")
  local argv="$1"
  case "$argv" in
    Set)
      check_file "${files[@]}"
      login=$(grep "pass" ${libexec}/UMBRELLA.login | tail -n 1)
      select opt in Password Disable Exit; do
        case "$opt" in
          Exit) exit 0 ;;
          Password)
            opt="Get"
            sed -i "s|$login|pass $opt|" $libexec/UMBRELLA.login
            log_data "Enable password"
            log "$D Enable password sucessfully!"
            break ;;
          Disable)
            opt=""
            sed -i "s|$login|pass $opt|" $libexec/UMBRELLA.login
            log_data "Disable password"
            log "$D Disable password sucessfully!"
            break ;;
          *)
            echo -e "${red}Error:${yellow} No valid option!. Try again.${default}"
            ;;
        esac
      done
      ;;
    New)
      while read -sp "New password: " pass && printf "\n" && [[ -z $pass ]]; do
        error "Input cannot be empty. Please try again."
        continue
      done
      while read -sp "Retype new password: " pass2 && printf "\n" && [[ -z $pass2 ]]
      do
        error "Input cannot be empty. Please try again."
        continue
      done
      if [[ $pass = $pass2 ]]; then
        local fpasswd=$(grep "PASSWORD" ${UMBRELLA}/passwd|tail -n 1)
        local encrypted=$(echo $pass|openssl enc -aes-256-cbc -md sha512 -a -pbkdf2 -iter 100000 -salt -pass pass:dynamic_key)
        sed -i "s|$fpasswd|PASSWORD : $encrypted|" ${UMBRELLA}/passwd

        log "Password saved successfully!.\e[0m\n"
      else
        error "Password do noy match."
        pass New
      fi
      log_data "Add new password"
      ;;
    Get)
      check_file "${files[@]}"
      local passwd=$(grep "PASSWORD" ${UMBRELLA}/passwd | tail -n 1)
      if [[ -z "$passwd" ]]; then
        error "No password found in the file."
        return 1
      fi

      local encrypted_pass=$(echo "$passwd" | awk '{print $NF}')
      if [[ -z "$encrypted_pass" ]]; then
        error "Encrypted password is empty."
        return 1
      fi
      decrypted_pass=$(echo "$encrypted_pass" | openssl enc -aes-256-cbc -md sha512 -a -d -pbkdf2 -iter 100000 -salt -pass pass:dynamic_key 2>/dev/null)
      if [[ $? -ne 0 ]]; then
        error "Failed to decrypt the password. Check the encryption format or key."
        return 1
      fi

      max_attempts=3
      attempt=0

      while read -sp "Password: " pass && [[ -z "$pass" ]]; do
        error "Input password!.\n"
        continue
      done
      until [[ "$pass" = "$decrypted_pass" ]] && printf "\n"; do
        attempt=$((attempt + 1))
        if [[ $attempt -ge $max_attempts ]]; then
          error "Maximum attempts reached. Exiting."
          log_data "Failed to input correct password after $max_attempts attempts."
          sleep 2
          pkill com.termux
        fi
        error "Retype the password"
        log_data "Error to get password (Attempt: $attempt)"
        pass=""
        while read -sp "Password: " pass && [[ -z "$pass" ]]; do
          error "Input password!.\n"
          continue
        done
      done
      log "$D Password sucessfully!\nWELCOME TO  U M B R E L L A  C O R P O R A T I O N"
      log_data "Input password successfully"
      ;;
  esac
}

export -f pass
