#!/usr/bin/bash

#COLORS:

export bold='\e[0;1m'
export red='\e[0;31m'
export default='\e[0m'
export yellow='\e[0;33m'
export green='\e[0;32m'
export blue='\e[0;34m'
export cyan='\e[0;36'
export gray='\e[0;37m'
export black='\e[0;30m'
export purple='\e[0;35m'
export underline='\e[4m'
export reverse='\e[7m'
export blink='\e[5m'
export dim='\e[2m'
export hidden='\e[8m'
#VARIABLES:         
export libexec="${HOME}/.UMBRELLA/libexec"
export UMBRELLA="${HOME}/.UMBRELLA/UMBRELLA"
export Zsh="${HOME}/.UMBRELLA/oh-my-zsh"
export BANNER="${HOME}/.UMBRELLA/UMBRELLA/BANNER"
export etc="${PREFIX}/etc"
export opt="${PREFIX}/opt"
export bin="${PREFIX}/etc/bin"
export share="${HOME}/.UMBRELLA/Share"
export LOCALHOST=$(ifconfig 2>&1|grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'|grep -v 255|tail -n 1)
export LPORT='3030'
export PULSE_SERVER='127.0.0.1'
export RPORT='80'
export whoami=$(whoami)
export version='v1.0.3 '
