#!/usr/bin/bash

#COLORS:

export white='\e[38;05;231m'
export bold='\e[0;1m'
export red='\e[0;31m'
export default='\e[0m'
export yellow='\e[0;33m'
export green='\e[38;05;106m'
export blue='\e[0;34m'
export cyan='\e[0;36m'
export gray='\e[0;37m'
export black='\e[0;30m'
export purple='\e[38;05;93m'
export orange='\e[38;05;130m'
export underline='\e[4m'
export reverse='\e[7m'
export blink='\e[5m'
export dim='\e[2m'
export hidden='\e[8m'
#VARIABLES:         
export libexec="${HOME}/.UMBRELLA/libexec"
export UMBRELLA="${HOME}/.UMBRELLA/UMBRELLA"
export Zsh="${HOME}/.UMBRELLA/oh-my-zsh"
export BANNER="${HOME}/.UMBRELLA/UMBRELLA/BANNER"
export etc="${PREFIX}/etc"
export opt="${PREFIX}/opt"
export bin="${PREFIX}/bin"
export share="${HOME}/.UMBRELLA/Share"
export LOCALHOST=$(ifconfig 2>&1|grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'|grep -v 255|tail -n 1)
export PULSE_SERVER='127.0.0.1'
export whoami=$(command whoami)
export version='v1.0.3 '
export E="$white[${red}✖$white]$red Error:\e[0m"
export D="$white[${green}✔$white]\e[0m"
export A="$white[${green}+$white]\e[0m"
export LOGFILE="${HOME}/.UMBRELLA/UMBRELLA/UMBRELLA.log"
