#!/usr/bin/bash

#COLORS:

export bold='\e[0;1m'
export red='\e[0;31m'
export default='\e[0m'
export yellow='\e[0;33m'
export green='\e[0;32m'
export blue='\e[0;34m;'
export cyan='\e[0;36'
export gray='\e[0;37m'
export black='\e[0;30m'
export purple='\e[0;35m'
export underline='\e[4m'
export reverse='\e[7m'
export blink='\e[5m'
export dim='\e[2m'
export hidden='\e[8m'
#VARIABLES:         
export log="/data/data/com.termux/files/usr/var/log/Umbrella.log"
export libexec="/data/data/com.termux/files/home/.UMBRELLA/libexec"
export UMBRELLA="/data/data/com.termux/files/home/.UMBRELLA/UMBRELLA"
export Zsh="/data/data/com.termux/files/home/.UMBRELLA/oh-my-zsh"
export BANNER="/data/data/com.termux/files/home/.UMBRELLA/UMBRELLA/BANNER"
export etc="/data/data/com.termux/files/usr/etc"
export opt="/data/data/com.termux/files/usr/opt"
export bin="/data/data/com.termux/files/usr/etc/bin"
export HOME="/data/data/com.termux/files/home"
export Share="/data/data/com.termux/files/home/.UMBRELLA/Share"
export User=$(grep -n 'set USER' '/data/data/com.termux/files/usr/etc/zshrc'|awk -F " " '{print $3}')
export LOCALHOST=$(ifconfig 2>&1|grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'|grep -v 255|tail -n 1)
export LPORT='3030'
export LOOPBACK='127.0.0.1'
export RPORT='80'
export whoami=$(whoami)
export version='v1.0.3 '
