#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("apksigner" "curl")

  if [ ! -x $PREFIX/bin/apktool ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "$A Installing dependencies for apktool ... "
    if curl -s https://raw.githubusercontent.com/rendiix/termux-apktool/main/install.sh | bash; then
      error "It could not be installed the package!."
      exit 1
    fi

    if ! pkg install apktool -y; then
      error "It could not be installed the package!."
      exit 1
    fi

    log "$D Done!"
    log "Please Execute:"
    echo
    log "apktool <argv>"
else
    log "$D Already Installed!"
fi
}

main
