#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/apktool ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for apktool...\e[0m\n"
    yes|pkg update && yes|pkg upgrade &>/dev/null;
    yes|pkg install apksigner curl;
    curl -s https://raw.githubusercontent.com/rendiix/termux-apktool/main/install.sh | bash
    yes|pkg update && yes|pkg upgrade &>/dev/null;
    yes|pkg install apktool
    printf "\e[1;38;5;253mDone!
    
    Please Execute:
    apktool <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi

