#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("ruby")
  if [ ! -x $PREFIX/bin/aquatone ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "$A Installing dependencies for aquatone ... "
    if ! gem install aquatone; then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/aquatone
    cat <<- Confg > $PREFIX/bin/aquatone
#!/usr/bin/bash
aquatone-discover "\$@"
Confg
    chmod 711 $PREFIX/bin/aquatone
    log "$D Done!"
    log "Please Execute:"
    echo
    log "aquatone <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
