#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/aquatone ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for aquatone...\e[0m\n"
    yes|pkg update && pkg upgrade &>/dev/null;
    yes|pkg install ruby
    gem install aquatone
    touch $PREFIX/bin/aquatone
    cat <<- Confg > $PREFIX/bin/aquatone
#!/usr/bin/bash
aquatone-discover "\$@"
Confg
    chmod 711 $PREFIX/bin/aquatone
    printf "\e[1;38;5;253mDone!
    Please Execute:

    aquatone <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
