#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/arjun ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for arjun...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python3
    python3 -m pip install --upgrade pip &>/dev/null;
    python3 -m pip install arjun
    printf "\e[1;38;5;253mDone!
    Please Execute:

    arjun <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
