#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("python3")
  if [ ! -x $PREFIX/bin/arjun ]; then
    install_dependencies "${bin[@]}"
    log "$A Installing dependencies for arjun ... "
    update_system
    if ! python3 -m pip install arjun; then
      error "It could not be installed the package!."
      exit 1
    fi
    log "$D Done!"
    log "Please Execute:"
    echo
    log "arjun <argv>"
else
  log "$D Already Installed!"
fi
}

main
