#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("nodejs" "wget" "ruby")

  if [ ! -x $PREFIX/bin/beef-xss ]; then
    install_dependencies "${bin[@]}"
    log "$A Installing dependencies for beef-xss ... "
    bash "${UMBRELLA}/Tools/metasploit"
    git clone https://github.com/beefproject/beef $PREFIX/opt/beef
    bundle "$PREFIX/opt/beef/install"
    rm "$PREFIX/opt/beef/config.yaml"
    rm "$PREFIX/opt/beef/extensions/social_engineering/mass_mailer/mass_mailer.rb"
    touch $PREFIX/bin/beef-xss
    cat <<- Confg >$PREFIX/bin/beef-xss
#!/bin/bash
beef="/data/data/com.termux/files/usr/opt/beef"
cd \${beef}
exec ruby "\${beef}/beef" "\$@"
Confg
    chmod 711 $PREFIX/bin/beef-xss
    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/beef-xss.zip -O $PREFIX/etc/beef-xss.zip; then
      if unzip "$PREFIX/etc/beef-xss.zip"; then
        mv "$PREFIX/etc/beef-xss/GeoIP" $PREFIX/opt/beef
        mv "$PREFIX/etc/beef-xss/mass_mailer.rb" "$PREFIX/opt/beef/extensions/social_engineering/mass_mailer"
        mv "$PREFIX/etc/beef-xss/config.yaml" $PREFIX/opt/beef
        mv "$PREFIX/etc/beef-xss/metasploit.rb" $PREFIX/opt/beef
        rm -rf "$PREFIX/etc/beef-xss"
        rm "$PREFIX/etc/beef-xss.zip"
      else
        error "It could not be installed the package!."
      exit 1
    fi
    else
      error "It could not be installed the package!."
      exit 1
    fi
    beefUser="UMBRELLA"
    beefPass="UMBRELLA"
    log "Username BEEf: "
    read -r User
    log "Password BEEf: "
    read -r Pass
    sed -i "s!${beefUser}!${User}!g" $PREFIX/opt/beef/config.yaml
    sed -i "s!${beefPass}!${Pass}!g" $PREFIX/opt/beef/config.yaml
    sed -i "s!${beefUser}!${User}!g" $PREFIX/opt/beef/metasploit.rb
    sed -i "s!${beefPass}!${Pass}!g" $PREFIX/opt/beef/metasploit.rb

    log "$D Done!"
    log "Please Execute:"
    echo
    log "beef-xss <argv>"
  else
    log "$D Already Installed!"
  fi
}
main
