#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/crunch ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for crunch...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install crunch
    printf "\e[1;38;5;253mDone!
    Please Execute:

    crunch <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
