#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033
[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }        
main() {
  local bin=("git" "python3")

  if [ ! -x $PREFIX/bin/cupp ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for cupp ... "

    update_system

    git clone https://github.com/Mebus/cupp $PREFIX/opt/cupp
    touch $PREFIX/bin/cupp
    cat <<- Confg > $PREFIX/bin/cupp
#!/usr/bin/bash
cupp="/data/data/com.termux/files/usr/opt/cupp"
cd \${cupp}
exec python3 "\${cupp}/cupp.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/cupp
    log "$D Done!"
    log "Please Execute:"
    echo
    log "cupp <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
