#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

if [ ! -x $PREFIX/bin/dirb ]; then
  log"Installing dependencies for dirb ... "
  if ! pkg install dirb -y; then
    error "It could not be installed the package!."
    exit 1
  fi
  log "$D Done!"
  log "Please Execute:"
  echo
  log "dirb <argv>"
else
  log "$D Already Installed!"
fi
