#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python" "wget")

  if [ ! -x ${bin}/ecuador-id ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for ecuador-id ... "
    update_system

    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/Ecuador-ID.zip -O $PREFIX/etc/Ecuador-ID.zip; then
      error "It could not be installed the package!."
      exit 1
    fi
    unzip "$PREFIX/etc/Ecuador-ID.zip"
    mv $PREFIX/etc/Ecuador-ID $PREFIX/opt
    rm $PREFIX/etc/Ecuador-ID.zip
    cd $PREFIX/opt/Ecuador-ID
    python3 -m pip install tabulate
    touch $PREFIX/bin/ecuador-id

    cat <<- Confg > $PREFIX/bin/ecuador-id
#!/bin/bash
EcuadorID="/data/data/com.termux/files/usr/opt/Ecuador-ID"
cd \${EcuadorID}
exec python3 "\${EcuadorID}/Ecuador-ID.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/ecuador-id
    log "$D Done!"
    log "Please Execute:"
    echo
    log "ecuador-id <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
