#!/usr/bin/bash
#
if [ ! -x ${bin}/ecuador-id ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for ecuador-id...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    yes|pkg install wget
    python3 -m pip install --upgrade pip &>/dev/null;
    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/Ecuador-ID.zip -O $PREFIX/etc/Ecuador-ID.zip
    cd $PREFIX/etc
    unzip Ecuador-ID.zip
    mv Ecuador-ID $PREFIX/opt
    rm -rf Ecuador-ID.zip
    cd $PREFIX/opt/Ecuador-ID
    python3 -m pip install tabulate
    touch $PREFIX/bin/ecuador-id
    cat <<- Confg > $PREFIX/bin/ecuador-id
#!/bin/bash
EcuadorID="/data/data/com.termux/files/usr/opt/Ecuador-ID"
cd \${EcuadorID}
exec python3 "\${EcuadorID}/Ecuador-ID.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/ecuador-id
    printf "\e[1;38;5;253mDone!
    Please Execute:

    ecuador-id\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi

