#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3")

  if [ ! -x $PREFIX/bin/email2pn ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for email2pn ... "

    update_system
    git clone https://github.com/martinvigo/email2phonenumber $PREFIX/opt/email2phonenumber
    cd $PREFIX/opt/email2phonenumber
    if ! python3 -m pip install -r requirements.txt;then
      error "It could not be installed the package!."
      exit 1
    fi

    touch $PREFIX/bin/email2pn
    cat <<- Confg $PREFIX/bin/email2pn
#!/bin/bash
email2pn="/data/data/com.termux/files/usr/opt/email2phonenumber"
cd \${email2pn}
exec python3 "\${email2pn}/email2phonenumber.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/email2pn
    log "$D Done!"
    log "Please Execute:"
    echo
    log "email2pn <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
