#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033
[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3")

  if [ ! -x $PREFIX/bin/evilurl ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for evilurl ... "

    update_system
    if ! python3 -m pip install python-nmap python-whois; then
      error "It could not be installed the package!."
      exit 1
    fi
    git clone https://github.com/UndeadSec/EvilURL $PREFIX/opt/EvilURL
    touch $PREFIX/bin/evilurl
    cat <<- Confg > $PREFIX/bin/evilurl
#!/bin/bash
evilurl="/data/data/com.termux/files/usr/opt/EvilURL"
cd \${evilurl}
exec python3 "\${evilurl}/evilurl.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/evilurl
    log "$D Done!"
    log "Please Execute:"
    echo
    log "hydra <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
