#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/exiftool ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for exiftool...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install exiftool
    printf "\e[1;38;5;253mDone!
    Please Execute:

    exiftool <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
