#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "curl")

  if [ ! -x $PREFIX/bin/fbuserid ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for fbuserid ... "

    update_system
    git clone https://github.com/Darkmux/fbuserid $PREFIX/opt/fbuserid
    cd $PREFIX/opt/fbuserid
    chmod 711 *.sh
    touch $PREFIX/bin/fbuserid
    cat <<- Confg $PREFIX/bin/fbuserid
#!/bin/bash
fbuserid="/data/data/com.termux/files/usr/opt/fbuserid"
cd \${fbuserid}
exec bash "\${fbuserid}/fbuserid.sh" "\$@"
Confg
    chmod 711 $PREFIX/bin/fbuserid
    log "$D Done!"
    log "Please Execute:"
    echo
    log "fbuserid <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
