#!/bin/bash
if [ ! -x $PREFIX/bin/fbuserid ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for fbuserid...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install curl
    git clone https://github.com/Darkmux/fbuserid $PREFIX/opt/fbuserid
    cd $PREFIX/opt/fbuserid
    chmod 711 *.sh
    touch $PREFIX/bin/fbuserid
    cat <<- Confg $PREFIX/bin/fbuserid
#!/bin/bash
fbuserid="/data/data/com.termux/files/usr/opt/fbuserid"
cd \${fbuserid}
exec bash "\${fbuserid}/fbuserid.sh" "\$@"
Confg
    chmod 711 $PREFIX/bin/fbuserid
    printf "\e[1;38;5;253mDone!
    Please Execute:

    fbuserid <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
