#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3" "android-tools" "python-cryptography")

  if [ ! -x $PREFIX/bin/ghost ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for ghost ... "

    update_system
    if ! python3 -m pip install git+https://github.com/EntySec/Ghost; then
      error "It could not be installed the package!."
      exit 1
    fi
    log "$D Done!"
    log "Please Execute:"
    echo
    log "ghost <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
