#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/ghost ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for ghost...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python3 android-tools git
    yes|pkg install python-cryptography
    python3 -m pip install --upgrade pip &>/dev/null;
    python3 -m pip install git+https://github.com/EntySec/Ghost
    printf "\e[1;38;5;253mDone!
    Please Execute:

    ghost <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi

