#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/gobuster ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for gobuster...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install golang
    git clone https://github.com/OJ/gobuster $PREFIX/opt/gobuster
    cd $PREFIX/opt/gobuster
    go get && go build
    ln -s $PREFIX/opt/gobuster/gobuster $PREFIX/bin/gobuster
    chmod 711 $PREFIX/bin/gobuster
    printf "\e[1;38;5;253mDone!
    Please Execute:

    gobuster <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
