#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "golang")

  if [ ! -x $PREFIX/bin/gobuster ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for gobuster ... "

    update_system
    git clone https://github.com/OJ/gobuster $PREFIX/opt/gobuster
    cd $PREFIX/opt/gobuster
    go get && go build
    ln -s $PREFIX/opt/gobuster/gobuster $PREFIX/bin/gobuster
    chmod 711 $PREFIX/bin/gobuster
    log "$D Done!"
    log "Please Execute:"
    echo
    log "gobuster <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
