#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3")

  if [ ! -x $PREFIX/bin/hashcrypt ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for hashcrypt ... "
    update_system
    git clone https://github.com/Darkmux/hashcrypt $PREFIX/opt/hashcrypt
    if ! python3 -m pip install -r "$PREFIX/opt/hashcrypt/requirements.txt"; then
      error "It could not be installed the package!."
      exit 1
    fi

    touch $PREFIX/bin/hashcrypt
    cat <<- Confg > $PREFIX/bin/hashcrypt
#!/bin/bash
hashcrypt="/data/data/com.termux/files/usr/opt/hashcrypt"
cd \${hashcrypt}
exec python3 "\${hashcrypt}/hashcrypt-v2.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/hashcrypt
    log "$D Done!"
    log "Please Execute:"
    echo
    log "hydra <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
