#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/buster ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for hash-buster...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/s0md3v/Hash-Buster $PREFIX/opt/Hash-Buster
    ln -s $PREFIX/opt/Hash-Buster/hash.py $PREFIX/bin/buster
    chmod 711 $PREFIX/bin/buster
    printf "\e[1;38;5;253mDone!
    Please Execute:

    buster <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
