#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/hash-id ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for hash-id...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/blackploit/hash-identifier $PREFIX/opt/hash-identifier
    touch $PREFIX/bin/hash-id
    cat <<- Confg > $PREFIX/bin/hash-id
#!/bin/bash
hashid="/data/data/com.termux/files/usr/opt/hash-identifier"
cd \${hashid}
exec python3 "\${hashid}/hash-id.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/hash-id
    printf "\e[1;38;5;253mDone!
    Please Execute:

    hash-id <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
