#!/usr/bin/bash
if [ ! -x $PREFIX/bin/hashcrypt ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for hashcrypt...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/Darkmux/hashcrypt $PREFIX/opt/hashcrypt
    cd $PREFIX/opt/hashcrypt
    python3 -m pip install -r requirements.txt
    touch $PREFIX/bin/hashcrypt
    cat <<- Confg > $PREFIX/bin/hashcrypt
#!/bin/bash
hashcrypt="/data/data/com.termux/files/usr/opt/hashcrypt"
cd \${hashcrypt}
exec python3 "\${hashcrypt}/hashcrypt-v2.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/hashcrypt
    printf "\e[1;38;5;253mDone!
    Please Execute:

    hashcrypt <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
