#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3")

  if [ ! -x $PREFIX/bin/hash-id ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for hash-id ... "
    update_system
    git clone https://github.com/blackploit/hash-identifier $PREFIX/opt/hash-identifier
    touch $PREFIX/bin/hash-id
    cat <<- Confg > $PREFIX/bin/hash-id
#!/bin/bash
hashid="/data/data/com.termux/files/usr/opt/hash-identifier"
cd \${hashid}
exec python3 "\${hashid}/hash-id.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/hash-id
    log "$D Done!"
    log "Please Execute:"
    echo
    log "hash-id <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
