#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/hydra ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for hydra...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python clang
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/vanhauser-thc/thc-hydra $PREFIX/opt/thc-hydra
    cd $PREFIX/opt/thc-hydra
    ./configure --prefix=$PREFIX
    make
    make install
    printf "\e[1;38;5;253mDone!
    Please Execute:

    hydra <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
