#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("x11-repo" "git" "python3" "clang" "make" "openssl" "openssl-tool" "wget" "coreutils" "gtk2" "gtk3")

  if [ ! -x $PREFIX/bin/hydra ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for hydra ... "
    update_system

    git clone https://github.com/vanhauser-thc/thc-hydra $PREFIX/opt/thc-hydra
    cd $PREFIX/opt/thc-hydra
    ./configure --prefix=$PREFIX
    make
    make install
    log "$D Done!"
    log "Please Execute:"
    echo
    log "hydra <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
