#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/iphunter ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for iphunter...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    yes|pkg install wget
    python3 -m pip install --upgrade pip &>/dev/null;
    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/iphunter.zip -O $PREFIX/etc/iphunter.zip
    cd $PREFIX/etc/
    unzip iphunter.zip
    mv iphunter $PREFIX/opt/
    rm -rf iphunter.zip
    cd $PREFIX/opt/iphunter
    python3 -m pip install -r requirements.txt &>/dev/null;
    touch $PREFIX/bin/iphunter
    cat <<- Confg > $PREFIX/bin/iphunter
#!/bin/bash
iphunter="/data/data/com.termux/files/usr/opt/iphunter"
cd \${iphunter}
exec python3 "\${iphunter}/iphunter.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/iphunter
    printf "\e[1;38;5;253mDone!
    Please Execute:

    iphunter\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
