#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("python3" "wget" "unzip")

  if [ ! -x $PREFIX/bin/iphunter ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for iphunter ... "
    update_system
    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/iphunter.zip -O $PREFIX/etc/iphunter.zip; then
      cd $PREFIX/etc/
      unzip "$PREFIX/etc/iphunter.zip"
      mv "$PREFIX/etc/iphunter" $PREFIX/opt/
      rm "$PREFIX/etc/iphunter.zip"
    else
      error "It could not be installed the package!."
      exit 1
    fi
    if ! python3 -m pip install -r "$PREFIX/opt/iphunter/requirements.txt"; then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/iphunter
    cat <<- Confg > $PREFIX/bin/iphunter
#!/bin/bash
iphunter="/data/data/com.termux/files/usr/opt/iphunter"
cd \${iphunter}
exec python3 "\${iphunter}/iphunter.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/iphunter
    log "$D Done!"
    log "Please Execute:"
    echo
    log "iphunter <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
