#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3" "make")
  if [ ! -x $PREFIX/bin/john ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for jhon ..."
    update_system
    git clone https://github.com/openwall/john $PREFIX/opt/john
    bash $PREFIX/opt/john/src/configure --prefix=$PREFIX
    make -s clean && make -sj4
    ln -s $PREFIX/opt/john/run $PREFIX/share/john
    ln -s $PREFIX/opt/john/run/john $PREFIX/bin/john
    ln -s $PREFIX/opt/john/run/zip2john $PREFIX/bin/zip2john
    ln -s $PREFIX/opt/john/run/rar2john $PREFIX/bin/rar2john
    ln -s $PREFIX/opt/john/run/ssh2john.py $PREFIX/bin/ssh2john

    log "$D Done!"
    log "Please Execute:"
    echo
    log "jhon <argv>"
  else
    log "$D Already Installed!"
  fi
}
main
