#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/john ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for jhon...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python clang
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/openwall/john $PREFIX/opt/john
    cd $PREFIX/opt/john/src
    ./configure --prefix=$PREFIX
    make -s clean && make -sj4
    ln -s $PREFIX/opt/john/run $PREFIX/share/john
    ln -s $PREFIX/opt/john/run/john $PREFIX/bin/john
    ln -s $PREFIX/opt/john/run/zip2john $PREFIX/bin/zip2john
    ln -s $PREFIX/opt/john/run/rar2john $PREFIX/bin/rar2john
    ln -s $PREFIX/opt/john/run/ssh2john.py $PREFIX/bin/ssh2john
    printf "\e[1;38;5;253mDone!
    Please Execute:

    jhon <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
