#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3" "wget" "unzip")

if [ ! -x $PREFIX/bin/magmaosint ]; then
    log "Installing dependencies for magmaosint ... "
    update_system
    if ! python3 -m pip install fuzzywuzzy; then
      error "It could not be installed the package!."
      exit 1
    fi
    if ! python3 -m pip install requests; then
      error "It could not be installed the package!."
      exit 1
    fi
    if ! python3 -m pip install google; then
      error "It could not be installed the package!."
      exit 1
    fi
    if ! python3 -m pip install colorama; then
      error "It could not be installed the package!."
      exit 1
    fi
    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/MagmaOsint.zip -O $PREFIX/etc/MagmaOsint.zip; then
    unzip "$PREFIX/etc/MagmaOsint.zip"
    mv "$PREFIX/etc/MagmaOsint" $PREFIX/opt
    rm "$PREFIX/etc/MagmaOsint.zip"
  else
    error "It could not be installed the package!."
      exit 1
    fi
    if python3 -m pip install -r "$PREFIX/opt/MagmaOsint/requirements.txt" &>/dev/null; then
      error "It could not be installed the package!."
      exit 1
    fi

    touch $PREFIX/bin/magmaosint
    cat <<- Confg > $PREFIX/bin/magmaosint
#!/bin/bash
magmaosint="/data/data/com.termux/files/usr/opt/MagmaOsint"
cd \${magmaosint}
exec python3 "\${magmaosint}/osint.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/magmaosint
    log "$D Done!"
    log "Please Execute:"
    echo
    log "magmaosint <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
