#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/magmaosint ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for magmaosint...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    yes|pkg install wget
    python3 -m pip install --upgrade pip &>/dev/null;
    python3 -m pip install fuzzywuzzy
    python3 -m pip install requests
    python3 -m pip install google
    python3 -m pip install colorama
    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/MagmaOsint.zip -O $PREFIX/etc/MagmaOsint.zip
    cd $PREFIX/etc
    unzip MagmaOsint.zip
    mv MagmaOsint $PREFIX/opt/
    rm -rf MagmaOsint.zip
    cd $PREFIX/opt/MagmaOsint
    python3 -m pip install -r requirements.txt &>/dev/null;
    touch $PREFIX/bin/magmaosint
    cat <<- Confg > $PREFIX/bin/magmaosint
#!/bin/bash
magmaosint="/data/data/com.termux/files/usr/opt/MagmaOsint"
cd \${magmaosint}
exec python3 "\${magmaosint}/osint.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/magmaosint
    printf "\e[1;38;5;253mDone!
    Please Execute:

    magmaosint\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
