#!/usr/bin/bash
#
if [ ! -x ${bin}/msfconsole ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for metasploit-framework...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg uninstall ruby

    if [ -d $HOME/metasploit-framework ]; then
        rm -rf $HOME/metasploit-framework
    fi
    if [ -d $PREFIX/opt/metasploit-framework ]; then
        rm -rf $PREFIX/opt/metasploit-framework
    fi
    if [ -x $PREFIX/bin/msfconsole ]; then
        rm $PREFIX/bin/msfconsole
    fi
    if [ -x $PREFIX/bin/msfvenom ]; then
        rm $PREFIX/bin/msfvenom
    fi

    yes|pkg install curl
    yes|pkg install wget
    wget https://github.com/gushmazuko/metasploit_in_termux/raw/master/metasploit.sh -O ~/metasploit.sh
    chmod 777 ~/metasploit.sh
    bash ~/metasploit.sh
    rm -rf metasploit.sh
    rm $PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb
    cp $HOME/.UMBRELLA/Share/code.rb $PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb
    printf "\e[1;38;5;253mDone!
    Please Execute:

    msfconsole <argv>

    ----- or -----

    msfvenom <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
