#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3")

  if [ ! -x $PREFIX/bin/metagoofil ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for metagoofil ... "
    update_system
    git clone https://github.com/opsdisk/metagoofil $PREFIX/opt/metagoofil
    if !python3 -m pip install -r "$PREFIX/opt/metagoofil/requirements.txt" &>/dev/null; then
      error "It could not be installed the package!."
      exit 1
    fi
    ln -s $PREFIX/opt/metagoofil/metagoofil.py $PREFIX/bin/metagoofil
    chmod 711 $PREFIX/bin/metagoofil
    log "$D Done!"
    log "Please Execute:"
    echo
    log "metagoofil <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
