#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "curl" "wget")
  if [ ! -x ${bin}/msfconsole ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for metasploit-framework ... "
    pkg uninstall ruby -y &>/dev/null;

    if [ -d $HOME/metasploit-framework ]; then rm -rf $HOME/metasploit-framework; fi
    if [ -d $PREFIX/opt/metasploit-framework ]; then rm -rf $PREFIX/opt/metasploit-framework; fi
    if [ -x $PREFIX/bin/msfconsole ]; then rm $PREFIX/bin/msfconsole; fi
    if [ -x $PREFIX/bin/msfvenom ]; then rm $PREFIX/bin/msfvenom; fi

    if ! wget https://github.com/gushmazuko/metasploit_in_termux/raw/master/metasploit.sh -O ~/metasploit.sh; then
      error "It could not be installed the package!."
    else
      chmod 777 ~/metasploit.sh
      bash ~/metasploit.sh
      rm metasploit.sh
    fi
    if [ -f "$HOME/.UMBRELLA/Share/code.rb" ]; then
      rm $PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb
      cp "$HOME/.UMBRELLA/Share/code.rb" "$PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry"
    else
      wget "raw.githubusercontent.com/Lawrence10Coroy/.UMBRELLA/refs/heads/master/Share/code.rb" -O "$PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb"
    fi
    log "$D Done!"
    log "Please Execute:"
    echo
    log "msfconsole <argv>"
    log "----- or -----"
    log "msfvenom <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
