#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "golang")

  if [ ! -x $PREFIX/bin/mosint ]; then
    log "Installing dependencies for mosint ... "
    install_dependencies "${bin[@]}"
    git clone https://github.com/alpkeskin/mosint $PREFIX/opt/mosint
    cd $PREFIX/opt/mosint
    go get && go build
    cd && ln -s $PREFIX/opt/mosint/mosint $PREFIX/bin/mosint
    chmod 777 $PREFIX/bin/mosint
    log "$D Done!"
    log "Please Execute:"
    echo
    log "mosint <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
