#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "nmap" "netcat-openbsd")

  if [ ! -x $PREFIX/bin/ncshare ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for ncshare ... "
    git clone https://github.com/whitehacks00/ncshare $PREFIX/opt/ncshare
    chmod 711 "$PREFIX/opt/ncshare/*.sh"
    touch $PREFIX/bin/ncshare
    cat <<- Confg > $PREFIX/bin/ncshare
#!/bin/bash
NCShare="/data/data/com.termux/files/usr/opt/ncshare"
cd \${NCShare}
exec bash "\${NCShare}/ncshare.sh" "\$@"
Confg
    chmod 711 $PREFIX/bin/ncshare
    log "$D Done!"
    log "Please Execute:"
    echo
    log "ncshare <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
