#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033
[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

if [ ! -x $PREFIX/bin/netcat ]; then
  bin=("nmap" "netcat-openbsd")
  log "Installing dependencies for netcat ... "
  install_dependencies "${bin[@]}"
  log "$D Done!"
  log "Please Execute:"
  echo
  log "ncat <argv>"
  log "------ or ------"
  log "netcat <argv>"
else
  log "$D Already Installed!"
fi
