#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/netcat ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for netcat...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install nmap netcat-openbsd
    printf "\e[1;38;5;253mDone!
    Please Execute:

    ncat <argv>

    ------ or ------
    
    netcat <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
