#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/nexfil ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for nexfil...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    python3 -m pip install tldextract
    python3 -m pip install aiohttp
    git clone https://github.com/thewhiteh4t/nexfil $PREFIX/opt/nexfil
    cd $PREFIX/opt/nexfil
    python3 -m pip install -r requirements.txt &>/dev/null;
    touch $PREFIX/bin/nexfil
    cat <<- Confg > $PREFIX/bin/nexfil
#!/bin/bash
nexfil="/data/data/com.termux/files/usr/opt/nexfil"
cd \${nexfil}
exec python3 "\${nexfil}/nexfil.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/nexfil
    printf "\e[1;38;5;253mDone!
    Please Execute:

    nexfil <argv>\e[0m\n";
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
