#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3")

  if [ ! -x $PREFIX/bin/nexfil ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for nexfil ... "
    update_system
    if ! python3 -m pip install tldextract; then
      error "It could not be installed the package!."
      exit 1
    fi
    if ! python3 -m pip install aiohttp; then
      error "It could not be installed the package!."
      exit 1
    fi
    git clone https://github.com/thewhiteh4t/nexfil $PREFIX/opt/nexfil
    if ! python3 -m pip install -r "$PREFIX/opt/nexfil/requirements.txt" &>/dev/null; then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/nexfil
    cat <<- Confg > $PREFIX/bin/nexfil
#!/bin/bash
nexfil="/data/data/com.termux/files/usr/opt/nexfil"
cd \${nexfil}
exec python3 "\${nexfil}/nexfil.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/nexfil
    log "$D Done!"
    log "Please Execute:"
    echo
    log "nexfil <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
