#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "perl")

  if [ ! -x $PREFIX/bin/nikto ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for nikto ... "
    git clone https://github.com/sullo/nikto $PREFIX/opt/nikto
    chmod 711 $PREFIX/opt/nikto/program/nikto.pl
    ln -s $PREFIX/opt/nikto/program/nikto.pl $PREFIX/bin/nikto
    chmod 711 $PREFIX/bin/nikto
    log "$D Done!"
    log "Please Execute:"
    echo
    log "nikto <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
