#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "nmap")

  if [ ! -x $PREFIX/bin/nmap ]; then
    log "Installing dependencies for nmap ... "
    install_dependencies "${bin[@]}"
    git clone https://github.com/scipag/vulscan $PREFIX/opt/scipag_vulscan
    ln -s $PREFIX/opt/scipag_vulscan $PREFIX/share/nmap/scripts/vulscan
    git clone https://github.com/vulnersCom/nmap-vulners $PREFIX/opt/nmap-vulners
    ln -s $PREFIX/opt/nmap-vulners $PREFIX/share/nmap/scripts/nmap-vulners
    log "$D Done!"
    log "Please Execute:"
    echo
    log "nmap <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
