#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/nmap ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for nmap...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install nmap
    git clone https://github.com/scipag/vulscan $PREFIX/opt/scipag_vulscan
    ln -s $PREFIX/opt/scipag_vulscan $PREFIX/share/nmap/scripts/vulscan
    git clone https://github.com/vulnersCom/nmap-vulners $PREFIX/opt/nmap-vulners
    ln -s $PREFIX/opt/nmap-vulners $PREFIX/share/nmap/scripts/nmap-vulners
    printf "\e[1;38;5;253mDone!
    Please Execute:

    nmap <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
