#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

if [ ! -x $PREFIX/bin/octosuite ]; then
    log "Installing dependencies for octosuite ... "
    update_system
    pkg install python3 -y
    if !python3 -m pip install octosuite; then
      error "It could not be installed the package!."
      exit 1
    fi
    log "$D Done!"
    log "Please Execute:"
    echo
    log "octosuite <argv>"
  else
    log "$D Already Installed!"
  fi
