#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python")

  if [ ! -x $PREFIX/bin/phoneinfoga ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for phoneinfoga ... "
    update_system
    git clone https://github.com/Darkmux/PhoneInfoga $PREFIX/opt/PhoneInfoga
    if ! python3 -m pip install -r $PREFIX/opt/PhoneInfoga/requirements.txt &>/dev/null; then
      error "It could not be installed the package!."
      exit 1
    fi
    if ! python3 -m pip install $PREFIX/opt/PhoneInfoga/config; then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/phoneinfoga
    cat <<- Confg > $PREFIX/bin/phoneinfoga
#!/bin/bash
phoneinfoga="/data/data/com.termux/files/usr/opt/PhoneInfoga"
cd \${phoneinfoga}
exec python3 "\${phoneinfoga}/phoneinfoga.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/phoneinfoga
    log "$D Done!"
    log "Please Execute:"
    echo
    log "phoneinfoga <argv>"
  else
    log "$D Already Installed!"
  fi
}

  main
