#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python3" "android-tools" "python-cryptography")

  if [ ! -x $PREFIX/bin/phonesploit ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for phonesploit-pro ... "
    update_system
    if [ -f "${UMBRELLA}/Tools/metasploit" ]; then
      bash "${UMBRELLA}/Tools/metasploit"
    else
      error "It could not be installed the package!."
      exit 1
    fi
    git clone https://github.com/AzeemIdrisi/PhoneSploit-Pro $PREFIX/opt/PhoneSploit-Pro
    touch $PREFIX/bin/phonesploit
    cat <<- Confg > $PREFIX/bin/phonesploit
#!/bin/bash
phonesploit="/data/data/com.termux/files/usr/opt/PhoneSploit-Pro"
cd \${phonesploit}
exec python3 "\${phonesploit}/phonesploitpro.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/phonesploit
    log "$D Done!"
    log "Please Execute:"
    echo
    log "phonesploit <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
