#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/phonesploit ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for phonesploit-pro...\e[0m\n"
    yes|pkg update && yes|pkg upgrade
    yes|pkg install python3 android-tools git
    yes|pkg install python-cryptography
    python3 -m pip install --upgrade pip &>/dev/null;
    UMBRELLA install metasploit
    git clone https://github.com/AzeemIdrisi/PhoneSploit-Pro $PREFIX/opt/PhoneSploit-Pro
    touch $PREFIX/bin/phonesploit
    cat <<- Confg > $PREFIX/bin/phonesploit
#!/bin/bash
phonesploit="/data/data/com.termux/files/usr/opt/PhoneSploit-Pro"
cd \${phonesploit}
exec python3 "\${phonesploit}/phonesploitpro.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/phonesploit
    printf "\e[1;38;5;253mDone!
    Please Execute:

    phonesploit <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
