#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/photon ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for photon...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/s0md3v/Photon $PREFIX/opt/Photon
    cd $PREFIX/opt/Photon
    python3 -m pip install -r requirements.txt &>/dev/null;
    touch $PREFIX/bin/photon
    cat <<- Confg > $PREFIX/bin/photon
#!/bin/bash
photon="/data/data/com.termux/files/usr/opt/Photon"
cd \${photon}
exec python3 "\${photon}/photon.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/photon
    printf "\e[1;38;5;253mDone!
    Please Execute:

    photon <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
