#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
local bin=("git" "python3")

if [ ! -x $PREFIX/bin/photon ]; then
    log "Installing dependencies for photon ... "
    install_dependencies "${bin[@]}"
    update_system
    git clone https://github.com/s0md3v/Photon $PREFIX/opt/Photon
    cd $PREFIX/opt/Photon
    if ! python3 -m pip install -r $PREFIX/opt/Photon/requirements.txt &>/dev/null; then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/photon
    cat <<- Confg > $PREFIX/bin/photon
#!/bin/bash
photon="/data/data/com.termux/files/usr/opt/Photon"
cd \${photon}
exec python3 "\${photon}/photon.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/photon
    log "$D Done!"
    log "Please Execute:"
    echo
    log "photon <argv>"
  else
    log "$D Already Installed!"
  fi
