#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
bin=("git" "python")

if [ ! -x $PREFIX/bin/protosint ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for protosint ..."
    update_system
    git clone https://github.com/pixelbubble/ProtOSINT $PREFIX/opt/ProtOSINT
    touch $PREFIX/bin/protosint
    cat <<- Confg > $PREFIX/bin/protosint
#!/bin/bash
protosint="/data/data/com.termux/files/usr/opt/ProtOSINT"
cd \${protosint}
exec python3 "\${protosint}/protosint.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/protosint
    log "$D Done!"
    log "Please Execute:"
    echo
    log "protosint <argv>"
  else
    log "$D Already Installed!"
  fi
