#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/protosint ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for protosint...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/pixelbubble/ProtOSINT $PREFIX/opt/ProtOSINT
    touch $PREFIX/bin/protosint
    cat <<- Confg > $PREFIX/bin/protosint
#!/bin/bash
protosint="/data/data/com.termux/files/usr/opt/ProtOSINT"
cd \${protosint}
exec python3 "\${protosint}/protosint.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/protosint
    printf "\e[1;38;5;253mDone!
    Please Execute:

    protosint <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
