#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
local bin=("git" "python3")

if [ ! -x $PREFIX/bin/pwnedornot ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for pwnedornot ... "
    update_system
    if ! python3 -m pip install html2text; then
      error "It could not be installed the package!."
      exit 1
    fi
    git clone https://github.com/thewhiteh4t/pwnedOrNot $PREFIX/opt/pwnedOrNot
    chmod 711 $PREFIX/opt/pwnedOrNot/*.sh
    bash $PREFIX/opt/pwnedOrNot/install.sh
    touch $PREFIX/bin/pwnedornot
    cat <<- Confg > $PREFIX/bin/pwnedornot
#!/bin/bash
pwnedornot="/data/data/com.termux/files/usr/opt/pwnedOrNot"
cd \${pwnedornot}
exec python3 "\${pwnedornot}/pwnedornot.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/pwnedornot
    log "$D Done!"
    log "Please Execute:"
    echo
    log "pwnedornot <argv>"
  else
    log "$D Already Installed!"
  fi
