#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
local bin=("git" "python")

if [ ! -x $PREFIX/bin/qrlink ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for qrlink ..."
    update_system
    if ! python3 -m pip install Pillow; then
      error "It could not be installed the package!."
      exit 1
    fi
    git clone https://github.com/Darkmux/qrlink $PREFIX/opt/qrlink
    cd $PREFIX/opt/qrlink
    chmod 777 $PREFIX/opt/qrlink/*.sh
    if ! python3 -m pip install -r $PREFIX/opt/qrlink/requirements.txt &>/dev/null;then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/qrlink
    cat <<- Confg $PREFIX/bin/qrlink
#!/bin/bash
qrlink="/data/data/com.termux/files/usr/opt/qrlink"
cd \${qrlink}
exec bash "\${qrlink}/qrlink.sh" "\$@"
Confg
    chmod 711 $PREFIX/bin/qrlink
    log "$D Done!"
    log "Please Execute:"
    echo
    log "qrlink <argv>"
  else
    log "$D Already Installed!"
  fi
