#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/recon-ng ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for recon-ng...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/lanmaster53/recon-ng $PREFIX/opt/recon-ng
    cd $PREFIX/opt/recon-ng
    chmod 711 recon-ng
    python3 -m pip install -r REQUIREMENTS
    touch $PREFIX/bin/recon-ng
    cat <<- Confg > $PREFIX/bin/recon-ng
#!/bin/bash
reconng="/data/data/com.termux/files/usr/opt/recon-ng"
cd \${reconng}
exec python3 "\${reconng}/recon-ng" "\$@"
Confg
    chmod 711 $PREFIX/bin/recon-ng
    printf "\e[1;38;5;253mDone!
    Please Execute:

    recon-ng\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
