#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
local bin=("git" "python3")

if [ ! -x $PREFIX/bin/recon-ng ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for recon-ng ... "
    update_system
    git clone https://github.com/lanmaster53/recon-ng $PREFIX/opt/recon-ng
    cd $PREFIX/opt/recon-ng
    chmod 711 $PREFIX/opt/recon-ng/recon-ng
    if !python3 -m pip install -r $PREFIX/opt/recon-ng/REQUIREMENTS; then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/recon-ng
    cat <<- Confg > $PREFIX/bin/recon-ng
#!/bin/bash
reconng="/data/data/com.termux/files/usr/opt/recon-ng"
cd \${reconng}
exec python3 "\${reconng}/recon-ng" "\$@"
Confg
    chmod 711 $PREFIX/bin/recon-ng
    log "$D Done!"
    log "Please Execute:"
    echo
    log "recon-gn <argv>"
  else
    log "$D Already Installed!"
  fi
