#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

bin=("git" "python3")

if [ ! -x $PREFIX/bin/recondog ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for recondog ... "
    update_system
    git clone https://github.com/s0md3v/ReconDog $PREFIX/opt/ReconDog
    cd $PREFIX/opt/ReconDog
    if ! python3 -m pip install -r $PREFIX/opt/ReconDog/requirements.txt &>/dev/null; then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/recondog
    cat <<- Confg > $PREFIX/bin/recondog
#!/bin/bash
recondog="/data/data/com.termux/files/usr/opt/ReconDog"
cd \${recondog}
exec python3 "\${recondog}/dog" "\$@"
Confg
    chmod 711 $PREFIX/bin/recondog
    log "$D Done!"
    log "Please Execute:"
    echo
    log "recondog <argv>"
  else
    log "$D Already Installed!"
  fi
