#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/redhawk ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for redhawk...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install php
    git clone https://github.com/Tuhinshubhra/RED_HAWK $PREFIX/opt/RED_HAWK
    touch $PREFIX/bin/redhawk
    cat <<- Confg > $PREFIX/bin/redhawk
    #!/bin/bash
redhawk="/data/data/com.termux/files/usr/opt/RED_HAWK"
cd \${redhawk}
exec php "\${redhawk}/rhawk.php" "\$@"
Confg
    chmod 711 $PREFIX/bin/redhawk
    printf "\e[1;38;5;253mDone!
    Please Execute:

    redhawk\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
