#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
local bin=("git" "php")

if [ ! -x $PREFIX/bin/redhawk ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for redhawk ... "
    update_system
    git clone https://github.com/Tuhinshubhra/RED_HAWK $PREFIX/opt/RED_HAWK
    touch $PREFIX/bin/redhawk
    cat <<- Confg > $PREFIX/bin/redhawk
    #!/bin/bash
redhawk="/data/data/com.termux/files/usr/opt/RED_HAWK"
cd \${redhawk}
exec php "\${redhawk}/rhawk.php" "\$@"
Confg
    chmod 711 $PREFIX/bin/redhawk
    log "$D Done!"
    log "Please Execute:"
    echo
    log "redhawk <argv>"
  else
    log "$D Already Installed!"
  fi
