#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/routersploit ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for routersploit...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python make clang rust
    python3 -m pip install --upgrade pip &>/dev/null;
    yes|pkg install python-cryptography python-bcrypt
    git clone https://github.com/threat9/routersploit $PREFIX/opt/routersploit
    cd $PREFIX/opt/routersploit
    python3 -m pip install -r requirements.txt &>/dev/null
    python3 -m pip install -r requirements-dev.txt &>/dev/null;
    python3 setup.py install
    touch $PREFIX/bin/routersploit
    cat <<- Confg > $PREFIX/bin/routersploit
#!/bin/bash
routersploit="/data/data/com.termux/files/usr/opt/routersploit"
cd \${routersploit}
exec python3 "\${routersploit}/rsf.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/routersploit
    printf "\e[1;38;5;253mDone!
    Please Execute:

    routersploit <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
