#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/saycheese ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for saycheese...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install wget php httrack openssh curl 
    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/saycheese.zip -O $PREFIX/tmp/saycheese.zip
    cd $PREFIX/tmp
    unzip saycheese.zip
    mv saycheese $PREFIX/opt
    rm -rf saycheese.zip
    cd $PREFIX/opt/saycheese
    chmod 711 *.sh
    ngrokserv
    ln -s $PREFIX/bin/ngrok $PREFIX/opt/saycheese/ngrok
    touch $PREFIX/bin/saycheese
    cat <<- Confg > $PREFIX/bin/saycheese
#!/bin/bash
saycheese="/data/data/com.termux/files/usr/opt/saycheese"
cd \${saycheese}
exec bash "\${saycheese}/saycheese.sh" "\$@"
Confg
    chmod 711 $PREFIX/bin/saycheese
    printf "\e[1;38;5;253mDone!
    Please Execute:

    saycheese <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
