#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "wget" "php" "httrack" "openssh" "curl" "unzip")

  if [ ! -x $PREFIX/bin/saycheese ]; then
    install_dependencies "${bin[@]}"
    log "Installing dependencies for saycheese ... "

    update_system
    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/saycheese.zip -O $PREFIX/opt/saycheese.zip; then
      unzip $PREFIX/opt/saycheese.zip
      rm -r saycheese.zip
      chmod 711 $PREFIX/opt/saycheese/*.sh
      ngrokserv
      ln -s $PREFIX/bin/ngrok $PREFIX/opt/saycheese/ngrok
    else
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/saycheese
    cat <<- Confg > $PREFIX/bin/saycheese
#!/bin/bash
saycheese="/data/data/com.termux/files/usr/opt/saycheese"
cd \${saycheese}
exec bash "\${saycheese}/saycheese.sh" "\$@"
Confg
    chmod 711 $PREFIX/bin/saycheese
    log "$D Done!"
    log "Please Execute:"
    echo
    log "saycheese <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
