#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python" "php" "curl" "wget" "openssh")

  if [ ! -x $PREFIX/bin/seeker ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for seeker ... "
    if ! python3 -m pip install packaging; then
      error "It could not be installed the package!."
      exit 1
    fi
    if ! python3 -m pip install requests; then
      error "It could not be installed the package!."
      exit 1
    fi
    git clone https://github.com/thewhiteh4t/seeker $PREFIX/opt/seeker
    chmod 711 $PREFIX/opt/seeker/install.sh
    bash $PREFIX/opt/seeker/install.sh
    touch $PREFIX/bin/seeker
    cat <<- Confg > $PREFIX/bin/seeker
#!/bin/bash
seeker="/data/data/com.termux/files/usr/opt/seeker"
cd \${seeker}
exec python3 "\${seeker}/seeker.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/seeker
    log "$D Done!"
    log "Please Execute:"
    echo
    log "seeker <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
