#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/seeker ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for seeker...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    yes|pkg install php
    yes|pkg install curl
    yes|pkg install wget
    yes|pkg install openssh
    pythob3 -m pip install --upgrade pip &>/dev/null;
    python3 -m pip install packaging
    python3 -m pip install requests
    git clone https://github.com/thewhiteh4t/seeker $PREFIX/opt/seeker
    cd $PREFIX/opt/seeker
    chmod 711 install.sh
    bash install.sh
    touch $PREFIX/bin/seeker
    cat <<- Confg > $PREFIX/bin/seeker
#!/bin/bash
seeker="/data/data/com.termux/files/usr/opt/seeker"
cd \${seeker}
exec python3 "\${seeker}/seeker.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/seeker
    printf "\e[1;38;5;253mDone!
    Please Execute:

    seeker <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
