#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

local bin=("python-pip" "python" "shodan")

if [ ! -x $PREFIX/bin/shodan ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for shodan ... "
    if ! python3 -m pip install shodan; then
      error "It could not be installed the package!."
      exit 1
    fi
    log "$D Done!"
    log "Please Execute:"
    echo
    log "shodan <argv>"
  else
    log "$D Already Installed!"
fi
