#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/shodan ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for shodan...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    yes|pkg install python-pip
    python3 -m pip install shodan
    printf "\e[1;38;5;253mDone!
    Please Execute:

    shodan <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
