#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/sigit ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for sigit...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    python3 -m pip install email_validator
    git clone https://github.com/termuxhackers-id/SIGIT $PREFIX/opt/SIGIT
    cd $PREFIX/opt/SIGIT
    chmod 711 install.sh
    bash install.sh
    printf "\e[1;38;5;253mDone!
    Please Execute:

    sigit <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
