#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

bin=("git" "python")

if [ ! -x $PREFIX/bin/sigit ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for sigit ... "
    if ! python3 -m pip install email_validator; then
      error "It could not be installed the package!."
      exit 1
    fi
    git clone https://github.com/termuxhackers-id/SIGIT $PREFIX/opt/SIGIT
    chmod 711 $PREFIX/opt/SIGIT/install.sh
    bash $PREFIX/opt/SIGIT/install.sh
    log "$D Done!"
    log "Please Execute:"
    echo
    log "sigit <argv>"
  else
    log "$D Already Installed!"
  fi
