#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/slowloris ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for slowloris...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/gkbrk/slowloris $PREFIX/opt/slowloris
    cd $PREFIX/opt/slowloris
    python3 setup.py install
    touch $PREFIX/bin/slowloris
    cat <<- Confg > $PREFIX/bin/slowloris
#!/bin/bash
slowloris="/data/data/com.termux/files/usr/opt/slowloris"
cd \${slowloris}
exec python3 "\${slowloris}/slowloris.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/slowloris
    printf "\e[1;38;5;253mDone!
    Please Execute:

    slowloris <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
