#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

bin=("git" "python3")

if [ ! -x $PREFIX/bin/slowloris ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for slowloris ... "
    git clone https://github.com/gkbrk/slowloris $PREFIX/opt/slowloris
    python3 $PREFIX/opt/slowloris/setup.py install
    touch $PREFIX/bin/slowloris
    cat <<- Confg > $PREFIX/bin/slowloris
#!/bin/bash
slowloris="/data/data/com.termux/files/usr/opt/slowloris"
cd \${slowloris}
exec python3 "\${slowloris}/slowloris.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/slowloris
    log "$D Done!"
    log "Please Execute:"
    echo
    log "slowloris <argv>"
  else
    log "$D Already Installed!"
  fi
