#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/speedtest ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for speedtest...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    python3 -m pip install speedtest-cli
    printf "\e[1;38;5;253mDone!
    Please Execute:

    speedtest <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
