#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/sublist3r ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for sublist3r...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    python3 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/aboul3la/Sublist3r $PREFIX/opt/Sublist3r
    cd $PREFIX/opt/Sublist3r
    python3 -m pip install -r requirements.txt &>/dev/null;
    touch $PREFIX/bin/sublist3r
    cat <<- Confg > $PREFIX/bin/sublist3r
#!/bin/bash
sublister="/data/data/com.termux/files/usr/opt/Sublist3r"
cd \${sublister}
exec python3 "\${sublister}/sublist3r.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/sublist3r
    printf "\e[1;38;5;253mDone!
    Please Execute:

    sublist3r <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
