#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

bin=("git" "python3")
if [ ! -x $PREFIX/bin/sublist3r ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for sublist3r ... "
    git clone https://github.com/aboul3la/Sublist3r $PREFIX/opt/Sublist3r
    if ! python3 -m pip install -r $PREFIX/opt/Sublist3r/requirements.txt 2>/dev/null; then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/sublist3r
    cat <<- Confg > $PREFIX/bin/sublist3r
#!/bin/bash
sublister="/data/data/com.termux/files/usr/opt/Sublist3r"
cd \${sublister}
exec python3 "\${sublister}/sublist3r.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/sublist3r
    log "$D Done!"
    log "Please Execute:"
    echo
    log "sublist3r <argv>"
  else
    log "$D Already Installed!"
  fi
