#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/tmate ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for tmate...\e[0m\n"
    yes|pkg update && yes|pkg upgrade
    yes|pkg install openssh tmate
    printf "\e[1;38;5;253mDone!
    Please Execute:

    tmate <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
