#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/trans ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for translate-shell...\e[0m\n"
    yes|pkg update && yes|pkg upgrade
    yes|pkg install translate-shell
    printf "\e[1;38;5;253mDone!
    Please Execute:

    trans <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
