#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/transwer ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for transwer...\e[0m\n"
    yes|pkg update && yes|pkg upgrade
    yes|pkg install translate-shell bat
    git clone https://github.com/Darkmux/transwer $PREFIX/opt/transwer
    cd $PREFIX/opt/transwer
    chmod 711 *.sh
    touch $PREFIX/bin/transwer
    cat <<- Confg > $PREFIX/bin/transwer
#!/bin/bash
transwer="/data/data/com.termux/files/usr/opt/transwer"
cd \${transwer}
exec bash "\${transwer}/transwer.sh" "\$@"
Confg
    chmod 711 $PREFIX/bin/transwer
    printf "\e[1;38;5;253mDone!
    Please Execute:

    transwer <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
