#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

bin=("translate-shell" "bat" "git")

if [ ! -x $PREFIX/bin/transwer ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for transwer ... "
    git clone https://github.com/Darkmux/transwer $PREFIX/opt/transwer
    chmod 711 $PREFIX/opt/transwer/*.sh
    touch $PREFIX/bin/transwer
    cat <<- Confg > $PREFIX/bin/transwer
#!/bin/bash
transwer="/data/data/com.termux/files/usr/opt/transwer"
cd \${transwer}
exec bash "\${transwer}/transwer.sh" "\$@"
Confg
    chmod 711 $PREFIX/bin/transwer
    log "$D Done!"
    log "Please Execute:"
    echo
    log "transwer <argv>"
  else
    log "$D Already Installed!"
  fi
