#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

bin=("translate-shell")
  if [ ! -x $PREFIX/bin/trans ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for translate-shell ... "
    log "$D Done!"
    log "Please Execute:"
    echo
    log "trans <argv>"
  else
    log "$D Already Installed!"
  fi
