#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python" "python-pillow")

  if [ ! -x $PREFIX/bin/vector ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for vector ... "
    if ! python3 -m pip install Pillow; then
      error "It could not be installed the package!."
      exit 1
    fi
    git clone https://github.com/thesaderror/vector $PREFIX/opt/vector
    if ! python3 -m pip install -r $PREFIX/opt/vector/requirements.txt 2>/dev/null; then
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/vector
    cat <<- Confg > $PREFIX/bin/vector
#!/bin/bash
vector="/data/data/com.termux/files/usr/opt/vector"
cd \${vector}
exec python3 "\${vector}/vector.py" "\$@"
Confg
    chmod 777 $PREFIX/bin/vector
    log "$D Done!"
    log "Please Execute:"
    echo
    log "vector <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
