#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/vim ] || [ ! -x $PREFIX/bin/vi ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for vim...\e[0m\n"
    yes|pkg install vim-python >/dev/null
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    rm -rf $HOME/.vimrc
    cp $HOME/.UMBRELLA/Share/.vimrc $HOME
    python -m pip --no-color --quiet --no-cache-dir install bpython
    python -m pip --no-color --quiet --no-cache-dir install jedi
    vim +PlugInstall +PlugUpdate +CocInstall +coc-json +coc-tsserver +coc-clangd +coc-sh +coc-python 2>>$PREFIX/var/log/Umbrella.log
  printf "\e[1;38;5;253mDone!
    Please Execute:

    vim \e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
