#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/vt-cli ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for virustotal-cli...\e[0m\n"
    yes|pkg update && yes|pkg upgrade
    yes|pkg install virustotal-cli
    printf "\e[1;38;5;253mDone!
    Please Execute:

    vt-cli <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
