#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

bin=("virustotal-cli")

  if [ ! -x $PREFIX/bin/vt-cli ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for virustotal-cli ... "
    log "$D Done!"
    log "Please Execute:"
    echo
    log "vt-cli <argv>"
  else
    log "$D Already Installed!"
  fi
