#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

bin=("python2" "tmate")

  if [ ! -x $PREFIX/bin/weeman ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for weeman ... "
    git clone https://github.com/evait-security/weeman $PREFIX/opt/weeman
    chmod 711 $PREFIX/opt/weeman/weeman.py
    touch $PREFIX/bin/weeman
    cat <<- Confg > $PREFIX/bin/weeman
#!/bin/bash
weeman="/data/data/com.termux/files/usr/opt/weeman"
cd \${weeman}
exec python2 "\${weeman}/weeman.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/weeman
    log "Installing dependencies for tmate ... "
    log "$D Done!"
    log "Please Execute:"
    echo
    log "weeman <argv>"
  else
    log "$D Already Installed!"
  fi
