#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/weeman ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for weeman...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python2
    python2 -m pip install --upgrade pip &>/dev/null;
    git clone https://github.com/evait-security/weeman $PREFIX/opt/weeman
    cd $PREFIX/opt/weeman
    chmod 711 weeman.py
    touch $PREFIX/bin/weeman
    cat <<- Confg > $PREFIX/bin/weeman
#!/bin/bash
weeman="/data/data/com.termux/files/usr/opt/weeman"
cd \${weeman}
exec python2 "\${weeman}/weeman.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/weeman
    printf "\e[1;38;5;253mDone!
    Please Execute:

    weeman\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
