#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("ruby" "git")

  if [ ! -x $PREFIX/bin/whatweb ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "$A Installing dependencies for whatweb ... "
    git clone https://github.com/urbanadventurer/WhatWeb $PREFIX/opt/WhatWeb
    bundle $PREFIX/opt/WhatWeb/install
    chmod 711 $PREFIX/opt/WhatWeb/whatweb
    touch $PREFIX/bin/whatweb
    cat <<- Confg > $PREFIX/bin/whatweb
#!/bin/bash
whatweb="/data/data/com.termux/files/usr/opt/WhatWeb"
cd \${whatweb}
exec ruby "\${whatweb}/whatweb" "\$@"
Confg
    chmod 711 $PREFIX/bin/whatweb
    log "$D Done!"
    log "Please Execute:"
    echo
    log "whatweb <argv>"
else
    log "$D Already Installed!"
fi
}

main
