#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/whatweb ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for whatweb...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install ruby
    git clone https://github.com/urbanadventurer/WhatWeb $PREFIX/opt/WhatWeb
    cd $PREFIX/opt/WhatWeb
    bundle install
    chmod 711 whatweb
    touch $PREFIX/bin/whatweb
    cat <<- Confg > $PREFIX/bin/whatweb
#!/bin/bash
whatweb="/data/data/com.termux/files/usr/opt/WhatWeb"
cd \${whatweb}
exec ruby "\${whatweb}/whatweb" "\$@"
Confg
    chmod 711 $PREFIX/bin/whatweb
    printf "\e[1;38;5;253mDone!
    Please Execute:

    whatweb <argv>\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
