#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

main() {
  local bin=("git" "python" "wget" "unzip")

  if [ ! -x $PREFIX/bin/wortex ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for wortex ... "
    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/wortex.zip -O $PREFIX/tmp/wortex.zip; then
      unzip $PREFIX/tmp/wortex.zip
      mv $PREFIX/tmp/wortex $PREFIX/opt
      rm -r $PREFIX/tmp/wortex.zip
    else
      error "It could not be installed the package!."
      exit 1
    fi
    touch $PREFIX/bin/wortex
    cat <<- Confg > $PREFIX/bin/wortex
#!/bin/bash
wortex="/data/data/com.termux/files/usr/opt/wortex"
cd \${wortex}
exec python3 "\${wortex}/wortex.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/wortex
    log "$D Done!"
    log "Please Execute:"
    echo
    log "wortex <argv>"
  else
    log "$D Already Installed!"
  fi
}

main
