#!/usr/bin/bash
#
if [ ! -x $PREFIX/bin/wortex ]; then
    echo -en "\e[1;4;38;5;253mInstalling dependencies for wortex...\e[0m\n"
    yes|pkg update && pkg upgrade
    yes|pkg install python
    yes|pkg install wget
    python3 -m pip install --upgrade pip &>/dev/null;
    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/wortex.zip -O $PREFIX/tmp/wortex.zip
    cd $PREFIX/tmp
    unzip wortex.zip
    mv wortex $PREFIX/opt
    rm -rf wortex.zip
    cd $PREFIX/opt/wortex
    touch $PREFIX/bin/wortex
    cat <<- Confg > $PREFIX/bin/wortex
#!/bin/bash
wortex="/data/data/com.termux/files/usr/opt/wortex"
cd \${wortex}
exec python3 "\${wortex}/wortex.py" "\$@"
Confg
    chmod 711 $PREFIX/bin/wortex
    printf "\e[1;38;5;253mDone!
    Please Execute:

    wortex\e[0m\n"
else
    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
fi
