#!/usr/bin/env bash
#Useful functions for customization of the Umbrella
source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }

bin=("python" "git")

  if [ ! -x $PREFIX/bin/xsstrike ]; then
    update_system
    install_dependencies "${bin[@]}"
    log "Installing dependencies for xsstrike ... "
    git clone https://github.com/s0md3v/XSStrike $PREFIX/opt/XSStrike
    if ! python3 -m pip install -r $PREFIX/opt/XSStrike/requirements.txt 2>/dev/null; then
      error "It could not be installed the package!."
      exit 1
    fi
    ln -s $PREFIX/opt/XSStrike/xsstrike.py $PREFIX/bin/xsstrike
    chmod 711 $PREFIX/bin/xsstrike
    log "$D Done!"
    log "Please Execute:"
    echo
    log "xsstrike <argv>"
  else
    log "$D Already Installed!"
  fi
